apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-function-with-testing
  namespace: default
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-function
    apps.tanzu.vmware.com/has-tests: true
spec:
  source:
    git:
      ref:
        branch: main
      url: https://github.com/drawsmcgraw/python-function
